export const marketsSeed = [
  // Lagos State
  {
    marketName: 'Balogun Market',
    marketLGA: 'Lagos Island Local Government Area',
    marketState: 'Lagos',
    marketEntity: 'Balogun Business Association (BBA)',
    marketGPS: '6.4549 3.3947',
  },
  {
    marketName: 'Tejuosho Market',
    marketLGA: 'Surulere Local Government Area',
    marketState: 'Lagos',
    marketEntity: 'Tejuosho Market Traders Association',
    marketGPS: '6.5022 3.3603',
  },
  {
    marketName: 'Mile 12 Market',
    marketLGA: 'Kosofe Local Government Area',
    marketState: 'Lagos',
    marketEntity: 'Mile 12 International Market Traders Association',
    marketGPS: '6.6010 3.3915',
  },
  {
    marketName: 'Oyingbo Market',
    marketLGA: 'Lagos Mainland Local Government Area',
    marketState: 'Lagos',
    marketEntity: 'Oyingbo Market Traders Association',
    marketGPS: '6.4698 3.3895',
  },
  {
    marketName: 'Ikeja Market',
    marketLGA: 'Ikeja Local Government Area',
    marketState: 'Lagos',
    marketEntity: 'Ikeja Market Traders Association',
    marketGPS: '6.5954 3.3390',
  },
  {
    marketName: 'Alaba International Market',
    marketLGA: 'Ojo Local Government Area',
    marketState: 'Lagos',
    marketEntity: 'Alaba International Amalgamated Traders Association',
    marketGPS: '6.4698 3.1850',
  },
  {
    marketName: 'Computer Village',
    marketLGA: 'Ikeja Local Government Area',
    marketState: 'Lagos',
    marketEntity:
      'Computer and Allied Products Dealers Association of Nigeria (CAPDAN)',
    marketGPS: '6.6018 3.3515',
  },
  {
    marketName: 'Idumota Market',
    marketLGA: 'Lagos Island Local Government Area',
    marketState: 'Lagos',
    marketEntity: 'Idumota Traders Association',
    marketGPS: '6.4530 3.3947',
  },
  {
    marketName: 'Oshodi Market',
    marketLGA: 'Oshodi-Isolo Local Government Area',
    marketState: 'Lagos',
    marketEntity: 'Oshodi Market Traders Association',
    marketGPS: '6.5571 3.3490',
  },
  {
    marketName: 'Ladipo Market',
    marketLGA: 'Mushin Local Government Area',
    marketState: 'Lagos',
    marketEntity: 'Ladipo Market Association',
    marketGPS: '6.5423 3.3667',
  },

  // Ogun State
  {
    marketName: 'Kuto Market',
    marketLGA: 'Abeokuta South Local Government Area',
    marketState: 'Ogun',
    marketEntity: 'Kuto Market Traders Association',
    marketGPS: '7.1475 3.3619',
  },
  {
    marketName: 'Iberekodo Market',
    marketLGA: 'Abeokuta North Local Government Area',
    marketState: 'Ogun',
    marketEntity: 'Iberekodo Market Traders Association',
    marketGPS: '7.1557 3.3452',
  },
  {
    marketName: 'Sagamu Market',
    marketLGA: 'Sagamu Local Government Area',
    marketState: 'Ogun',
    marketEntity: 'Sagamu Market Traders Association',
    marketGPS: '6.8389 3.6483',
  },
  {
    marketName: 'Ijebu-Ode Market',
    marketLGA: 'Ijebu Ode Local Government Area',
    marketState: 'Ogun',
    marketEntity: 'Ijebu-Ode Market Traders Association',
    marketGPS: '6.8186 3.9172',
  },
  {
    marketName: 'Ota Market',
    marketLGA: 'Ado-Odo/Ota Local Government Area',
    marketState: 'Ogun',
    marketEntity: 'Ota Market Traders Association',
    marketGPS: '6.6804 3.2356',
  },

  // Oyo State
  {
    marketName: 'Bodija Market',
    marketLGA: 'Ibadan North Local Government Area',
    marketState: 'Oyo',
    marketEntity: 'Bodija Market Traders Association',
    marketGPS: '7.4167 3.9000',
  },
  {
    marketName: 'Dugbe Market',
    marketLGA: 'Ibadan South-West Local Government Area',
    marketState: 'Oyo',
    marketEntity: 'Dugbe Market Traders Association',
    marketGPS: '7.3833 3.8833',
  },
  {
    marketName: 'Gbagi Market',
    marketLGA: 'Ibadan North-West Local Government Area',
    marketState: 'Oyo',
    marketEntity: 'Gbagi Market Traders Association',
    marketGPS: '7.3964 3.8905',
  },
  {
    marketName: 'Oje Market',
    marketLGA: 'Ibadan North Local Government Area',
    marketState: 'Oyo',
    marketEntity: 'Oje Market Traders Association',
    marketGPS: '7.3922 3.8958',
  },
  {
    marketName: 'Oyo Market',
    marketLGA: 'Oyo East Local Government Area',
    marketState: 'Oyo',
    marketEntity: 'Oyo Market Traders Association',
    marketGPS: '7.8510 3.9320',
  },
];