export const marketsSeed = [
  // Lagos State
  {
    marketName: 'Balogun Market',
    marketLGA: 'Lagos Island Local Government Area',
    marketState: 'Lagos',
    marketEntity: 'Socialander',
    marketGPS: '6.4549 3.3947',
    popularLandmark: 'CMS / Marina Axis',
    marketBuildingsType: 'Mixed (open stalls + lock-up shops)',
    powerSource: 'PHCN + generators',
    gridInfrastructure: 'Moderate (dense informal wiring, shared meters)',
      LGA_Eligibility: true,
    marketDescription:
      'Large wholesale and retail market with dense trading activity across textiles, fashion accessories, and general goods within a mixed open and lock-up shop structure.',
  },
  {
    marketName: 'Tejuosho Market',
    marketLGA: 'Surulere Local Government Area',
    marketState: 'Lagos',
    marketEntity: 'Socialander',
    marketGPS: '6.5022 3.3603',
    popularLandmark: 'Tejuosho Ultra-Modern Market Complex',
    marketBuildingsType: 'Modern structured mall-style stalls',
    powerSource: 'PHCN + backup generators',
    gridInfrastructure: 'Organized internal wiring system',
      LGA_Eligibility: true,
    marketDescription:
      'Organized modern market complex with structured retail units primarily focused on fashion, fabrics, and consumer goods.',
  },
  {
    marketName: 'Mile 12 Market',
    marketLGA: 'Kosofe Local Government Area',
    marketState: 'Lagos',
    marketEntity: 'Socialander',
    marketGPS: '6.6010 3.3915',
    popularLandmark: 'Mile 12 Bridge',
    marketBuildingsType: 'Open-air market stalls',
    powerSource: 'Generators (primary) + limited PHCN',
    gridInfrastructure: 'Weak (temporary wiring, high load sharing)',
      LGA_Eligibility: false,
    marketDescription:
      'High-volume open-air food distribution market focused on perishable goods such as fruits, vegetables, and agricultural produce.',
  },
  {
    marketName: 'Oyingbo Market',
    marketLGA: 'Lagos Mainland Local Government Area',
    marketState: 'Lagos',
    marketEntity: 'Purple Stardust',
    marketGPS: '6.4698 3.3895',
    popularLandmark: 'Oyingbo Bus Terminal',
    marketBuildingsType: 'Mixed (open + semi-structured shops)',
    powerSource: 'PHCN + generators',
    gridInfrastructure: 'Moderate (old wiring system)',
      LGA_Eligibility: true,
    marketDescription:
      'Central urban market serving both retail and wholesale buyers with a mix of foodstuff and household goods.',
  },
  {
    marketName: 'Ikeja Market',
    marketLGA: 'Ikeja Local Government Area',
    marketState: 'Lagos',
    marketEntity: 'Purple Stardust',
    marketGPS: '6.5954 3.3390',
    popularLandmark: 'Allen Avenue Axis',
    marketBuildingsType: 'Structured lock-up shops + open sections',
    powerSource: 'PHCN + generators',
    gridInfrastructure: 'Relatively stable (commercial grid access)',
      LGA_Eligibility: true,
    marketDescription:
      'Urban retail market serving surrounding residential and commercial districts with mixed consumer goods and services.',
  },
  {
    marketName: 'Alaba International Market',
    marketLGA: 'Ojo Local Government Area',
    marketState: 'Lagos',
    marketEntity: 'Purple Stardust',
    marketGPS: '6.4698 3.1850',
    popularLandmark: 'Alaba Rago / Badagry Expressway',
    marketBuildingsType: 'Dense lock-up shops + warehouses',
    powerSource: 'Heavy generator dependency',
    gridInfrastructure: 'High-load informal wiring system',
      LGA_Eligibility: true,
    marketDescription:
      'Major electronics and wholesale market specializing in electronics, appliances, and imported goods with large trading warehouses.',
  },
  {
    marketName: 'Computer Village',
    marketLGA: 'Ikeja Local Government Area',
    marketState: 'Lagos',
    marketEntity: 'Intense Digital',
    marketGPS: '6.6018 3.3515',
    popularLandmark: 'Sheraton Hotel Axis',
    marketBuildingsType: 'High-density lock-up shops',
    powerSource: 'PHCN + generators',
    gridInfrastructure: 'Moderate (commercial grid, overloaded)',
      LGA_Eligibility: true,
    marketDescription:
      'Technology and electronics trading hub focused on mobile devices, computers, accessories, and repair services.',
  },
  {
    marketName: 'Idumota Market',
    marketLGA: 'Lagos Island Local Government Area',
    marketState: 'Lagos',
    marketEntity: 'Intense Digital',
    marketGPS: '6.4530 3.3947',
    popularLandmark: 'Tinubu Square',
    marketBuildingsType: 'High-density lock-up shops + street stalls',
    powerSource: 'Generators (dominant)',
    gridInfrastructure: 'Weak (aged and overloaded wiring)',
      LGA_Eligibility: true,
    marketDescription:
      'Dense commercial trading area with strong focus on fashion, textiles, and wholesale distribution within crowded urban structures.',
  },
  {
    marketName: 'Oshodi Market',
    marketLGA: 'Oshodi-Isolo Local Government Area',
    marketState: 'Lagos',
    marketEntity: 'Wild Fusion',
    marketGPS: '6.5571 3.3490',
    popularLandmark: 'Oshodi Transport Interchange',
    marketBuildingsType: 'Open stalls + transport-side kiosks',
    powerSource: 'Generators + limited PHCN',
    gridInfrastructure: 'Poor to moderate (unstable supply)',
      LGA_Eligibility: false,
    marketDescription:
      'High-traffic commercial and transport-linked market offering fast-moving consumer goods and informal retail services.',
  },
  {
    marketName: 'Ladipo Market',
    marketLGA: 'Mushin Local Government Area',
    marketState: 'Lagos',
    marketEntity: 'Ziza Digital',
    marketGPS: '6.5423 3.3667',
    popularLandmark: 'Ladipo Auto Parts Axis',
    marketBuildingsType: 'Open yards + warehouses',
    powerSource: 'Generators (primary)',
    gridInfrastructure: 'Low (industrial informal wiring)',
      LGA_Eligibility: true,
    marketDescription:
      'Automotive spare parts and mechanical goods market serving vehicle repair and maintenance businesses.',
  },

  // Ogun State
  {
    marketName: 'Kuto Market',
    marketLGA: 'Abeokuta South Local Government Area',
    marketState: 'Ogun',
    marketEntity: 'Ziza Digital',
    marketGPS: '7.1475 3.3619',
    popularLandmark: 'MKO Abiola Way',
    marketBuildingsType: 'Open stalls + small lock-ups',
    powerSource: 'PHCN + generators',
    gridInfrastructure: 'Moderate',
      LGA_Eligibility: true,
    marketDescription:
      'Local mixed retail market serving foodstuff, household goods, and small-scale trading activities.',
  },
  {
    marketName: 'Iberekodo Market',
    marketLGA: 'Abeokuta North Local Government Area',
    marketState: 'Ogun',
    marketEntity: 'Ziza Digital',
    marketGPS: '7.1557 3.3452',
    popularLandmark: 'Iberekodo Junction',
    marketBuildingsType: 'Open-air stalls',
    powerSource: 'Mostly generators',
    gridInfrastructure: 'Weak',
      LGA_Eligibility: true,
    marketDescription:
      'Traditional open market primarily focused on daily foodstuffs and small retail trading.',
  },
  {
    marketName: 'Sagamu Market',
    marketLGA: 'Sagamu Local Government Area',
    marketState: 'Ogun',
    marketEntity: 'Socialander',
    marketGPS: '6.8389 3.6483',
    popularLandmark: 'Sagamu Interchange',
    marketBuildingsType: 'Mixed (open + semi-structured)',
    powerSource: 'PHCN + generators',
    gridInfrastructure: 'Moderate',
      LGA_Eligibility: true,
    marketDescription:
      'Regional commercial market supporting local trade in foodstuff, clothing, and household goods.',
  },
  {
    marketName: 'Ijebu-Ode Market',
    marketLGA: 'Ijebu Ode Local Government Area',
    marketState: 'Ogun',
    marketEntity: 'Purple Stardust',
    marketGPS: '6.8186 3.9172',
    popularLandmark: 'Ita-Ale Area',
    marketBuildingsType: 'Open stalls + lock-ups',
    powerSource: 'PHCN + generators',
    gridInfrastructure: 'Moderate',
      LGA_Eligibility: true,
    marketDescription:
      'Central town market serving agricultural produce, food items, and general merchandise.',
  },
  {
    marketName: 'Ota Market',
    marketLGA: 'Ado-Odo/Ota Local Government Area',
    marketState: 'Ogun',
    marketEntity: 'Purple Stardust',
    marketGPS: '6.6804 3.2356',
    popularLandmark: 'Sango Ota Axis',
    marketBuildingsType: 'Open market + roadside shops',
    powerSource: 'Generators (primary)',
    gridInfrastructure: 'Weak',
      LGA_Eligibility: true,
    marketDescription:
      'Busy roadside market serving commuters and residents with foodstuff and daily consumer goods.',
  },

  // Oyo State
  {
    marketName: 'Bodija Market',
    marketLGA: 'Ibadan North Local Government Area',
    marketState: 'Oyo',
    marketEntity: 'Ziza Digital',
    marketGPS: '7.4167 3.9000',
    popularLandmark: 'University of Ibadan Axis',
    marketBuildingsType: 'Open stalls + structured sections',
    powerSource: 'PHCN + generators',
    gridInfrastructure: 'Moderate',
      LGA_Eligibility: true,
    marketDescription:
      'Major food distribution market supplying grains, meat, and household food items within Ibadan.',
  },
  {
    marketName: 'Dugbe Market',
    marketLGA: 'Ibadan South-West Local Government Area',
    marketState: 'Oyo',
    marketEntity: 'Ziza Digital',
    marketGPS: '7.3833 3.8833',
    popularLandmark: 'Cocoa House / Dugbe Business District',
    marketBuildingsType: 'Structured commercial buildings',
    powerSource: 'PHCN + generators',
    gridInfrastructure: 'Relatively stable',
      LGA_Eligibility: true,
    marketDescription:
      'Central business and retail district with structured shops offering fashion, banking access, and services.',
  },
  {
    marketName: 'Gbagi Market',
    marketLGA: 'Ibadan North-West Local Government Area',
    marketState: 'Oyo',
    marketEntity: 'Wild Fusion',
    marketGPS: '7.3964 3.8905',
    popularLandmark: 'Iwo Road Axis',
    marketBuildingsType: 'Large open market stalls',
    powerSource: 'Generators (primary)',
    gridInfrastructure: 'Weak',
      LGA_Eligibility: false,
    marketDescription:
      'Large open trading market focused on clothing, textiles, and general consumer goods.',
  },
  {
    marketName: 'Oje Market',
    marketLGA: 'Ibadan North Local Government Area',
    marketState: 'Oyo',
    marketEntity: 'Wild Fusion',
    marketGPS: '7.3922 3.8958',
    popularLandmark: 'Beere Junction',
    marketBuildingsType: 'Traditional open market',
    powerSource: 'PHCN + generators',
    gridInfrastructure: 'Moderate',
      LGA_Eligibility: true,
    marketDescription:
      'Traditional market serving foodstuff and everyday household trading activities.',
  },
  {
    marketName: 'Oyo Market',
    marketLGA: 'Oyo East Local Government Area',
    marketState: 'Oyo',
    marketEntity: 'Wild Fusion',
    marketGPS: '7.8510 3.9320',
    popularLandmark: 'Oyo Town Central Area',
    marketBuildingsType: 'Open stalls',
    powerSource: 'Mostly generators',
    gridInfrastructure: 'Weak',
      LGA_Eligibility: false,
    marketDescription:
      'Local town market serving daily food and essential household goods.',
  },
];
